From: Ganga Ram <Ganga.Ram@tii.ae> Date: Wed, 05 July 2023 06:15:22 +0400 Subject: [PATCH] Riscv-Fix-build-against-binutils-2.38
The following description is copied from the equivalent patch for the
Linux Kernel proposed by Aurelien Jarno:

From version 2.38, binutils default to ISA spec version 20191213. This
means that the csr read/write (csrr*/csrw*) instructions and fence.i
instruction has separated from the `I` extension, become two standalone
extensions: Zicsr and Zifencei. As the kernel uses those instruction,
this causes the following build failure:

arch/riscv/lib/cache.c:12: Error: unrecognized opcode `fence.i', extension `zifencei' required
arch/riscv/cpu/cpu.c:94: Error: unrecognized opcode `csrs sstatus,a5', extension `zicsr' required
arch/riscv/cpu/cpu.c:95: Error: unrecognized opcode `csrw 0x003,0', extension `zicsr' required

More detail: https://patchwork.ozlabs.org/series/283391/mbox/

Signed-off-by: Ganga Ram <Ganga.Ram@tii.ae>